version: "3.7"

services:

  kltest:
    build:
      dockerfile: Dockerfile
      context: ./
    image: kltest
    restart: always
    network_mode: host
    environment:
      - CONSUL_HTTP_ADDR=127.0.0.1:8500
    volumes:
      - ./configs:/data/conf
#    logging:
#      driver: loki
#      options:
#        loki-url: 'http://db.kylan.pro:3100/api/prom/push'