version: "3.7"

services:

  kratos-layout:
    build:
      dockerfile: Dockerfile
      context: ./
    image: kratos-layout
    restart: always
    ports:
      - "9000:9000"
    environment:
      - CONSUL_HTTP_ADDR=127.0.0.1:8500
    volumes:
      - ./configs:/data/conf
